---
include: [_headers, _redirects]

name: "zircus"

social:
  - name: 'Email'
    url: 'mailto:support@zircus.ca'
    label:
      en: 'Send us an email'
      fr: 'Envoyez-nous un courriel'
    icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="footer__social_icon"><path d="M4 4h16c1.1 0 2 .9 2 2v12c0 1.1-.9 2-2 2H4c-1.1 0-2-.9-2-2V6c0-1.1.9-2 2-2z" ></path><polyline points="22,6 12,13 2,6"></polyline></svg>'
  - name: 'Instagram'
    url: 'https://www.instagram.com/zircusapparel/'
    label:
      en: 'View our Instagram page'
      fr: 'Voir notre page Instagram'
    icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="footer__social_icon"><rect x="2" y="2" width="20" height="20" rx="5" ry="5"></rect><path d="M16 11.37A4 4 0 1 1 12.63 8 4 4 0 0 1 16 11.37z"></path><line x1="17.5" y1="6.5" x2="17.51" y2="6.5"></line></svg>'
  - name: 'Facebook'
    url: 'https://www.facebook.com/zircusapparel/'
    label:
      en: 'View our Facebook page'
      fr: 'Voir notre page Facebook'
    icon: '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="footer__social_icon"><path d="M18 2h-3a5 5 0 0 0-5 5v3H7v4h3v8h4v-8h3l1-4h-4V7a1 1 0 0 1 1-1h3z"></path></svg>'

lang:
  en:
    name: 'en'
    home_link_path: '/'
    home_link: 'Zircus Home Page'
    footer_text: 'An inspiring underwear brand, queer owned & sewn on Vancouver Island.'
    skip_link: 'Skip to main content'
    lang_dropdown: 'Select language'
    close_notification: 'Close notification'
    back_to_top: 'Back to top of page'
    close_full_image: 'Close full view'
  fr:
    name: 'fr'
    home_link_path: '/fr'
    home_link: "Zircus Page d'accueil"
    footer_text: "Une marque de sous-vêtements inspirante, queer appartenant et cousu 
      sur l'île de Vancouver."
    skip_link: 'Passer au contenu principal'
    lang_dropdown: 'Sélectionnez la langue'
    close_notification: 'Fermez notification'
    back_to_top: 'Retour au haut de la page'
    close_full_image: 'Fermer la vue pleine grandeur'

collections:
  products:
    output: true

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
