---
include: [_headers, _redirects]

name: "zircus"
base: 'https://zircus.netlify.app'

collections:
  products:
    output: true

sass:
  style: compressed

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
