---
include: [_headers, _redirects]

name: "zircus"

lang:
  en:
    name: 'en'
    home_link_path: '/'
    home_link: 'Zircus Home Page'
    footer_text: 'An inspiring underwear brand, queer owned & sewn on Vancouver Island.'
  fr:
    name: 'fr'
    home_link_path: '/fr'
    home_link: "Zircus Page d'accueil"
    footer_text: "Une marque de sous-vêtements inspirante, queer appartenant et cousu 
      sur l'île de Vancouver."

collections:
  products:
    output: true

defaults:
  - scope:
      path: ""
      type: "products"
    values:
      layout: "product"
